{
 "title": "mekstack",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Nodes",
    "query": "controller-0 : 10.4.20.10, compute-1 : 10.4.20.101, compute-2 : 10.4.20.102 "
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nova",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Neutron",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Keystone",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_identity_up" }
   ]
  },
  {
   "title": "Glance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_glance_up" }
   ]
  },
  {
   "title": "Octavia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_loadbalancer_up" }
   ]
  },
  {
   "title": "Designate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openstack_designate_up" }
   ]
  },
  {
   "title": "Haproxy backends",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Down" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(haproxy_backend_up - 1)", "legendFormat": "{{ backend }}" }
   ]
  },
  {
   "title": "Libvirt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Down" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(libvirt_up - 1)" }
   ]
  },
  {
   "title": "Rabbitmq incoming",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[2m]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Unacknowledged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info)"
    }
   ]
  },
  {
   "title": "Rabbit memory available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rabbitmq_resident_memory_limit_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info) -\n(rabbitmq_process_resident_memory_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Nova memory ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_available_bytes)",
     "legendFormat": "avail"
    },
    {
     "expr": "sum(openstack_nova_memory_used_bytes)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Nova disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_local_storage_available_bytes)",
     "legendFormat": "avail"
    },
    {
     "expr": "sum(openstack_nova_local_storage_used_bytes)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "vCPU used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_nova_vcpus_used)" }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_glance_images)" }
   ]
  },
  {
   "title": "Loadbalancers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_loadbalancer_total_loadbalancers)"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_networks) "
    }
   ]
  },
  {
   "title": "Floating IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_floating_ips) "
    }
   ]
  },
  {
   "title": "Galera InnoDB Pages rw",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{operation!~\".*read|updated\"}[2m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{operation=\"read\"}[2m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Haproxy uplink",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total[2m]))",
     "legendFormat": "down"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total[2m]))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "vCPU overcommit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_nova_vcpus_used)/sum(openstack_nova_vcpus_available))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms)",
     "legendFormat": "running vms"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_identity_users)" }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects)"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_neutron_routers)" }
   ]
  },
  {
   "title": "Subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_neutron_subnets)" }
   ]
  },
  {
   "title": "DNS Zones",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(openstack_designate_zones)" }
   ]
  },
  {
   "title": "DNS Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_designate_recordsets)"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "node" },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!='idle', instance=\"${node:raw}:9100\"}[2m])) * 100 / 7",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "node_load1{instance=\"${node:raw}:9100\"}",
     "legendFormat": "short"
    },
    {
     "expr": "node_load5{instance=\"${node:raw}:9100\"}",
     "legendFormat": "medium"
    },
    {
     "expr": "node_load15{instance=\"${node:raw}:9100\"}",
     "legendFormat": "long"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"${node:raw}:9100\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "-rate(node_disk_written_bytes_total{instance=\"${node:raw}:9100\", device='md0'}[2m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"${node:raw}:9100\"}",
     "legendFormat": "total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"${node:raw}:9100\"} - node_memory_MemFree_bytes{instance=\"${node:raw}:9100\"} - node_memory_Buffers_bytes{instance=\"${node:raw}:9100\"} - node_memory_Cached_bytes{instance=\"${node:raw}:9100\"})",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"${node:raw}:9100\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"${node:raw}:9100\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"${node:raw}:9100\", mountpoint=\"/\"}",
     "legendFormat": "avail"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"${node:raw}:9100\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"${node:raw}:9100\", mountpoint=\"/\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"${node:raw}:9100\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage for $node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "repeat": "node",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "rate(container_cpu_usage_seconds_total{name!=\"\", instance=\"${node:raw}:18080\"}[2m])",
       "legendFormat": "{{name}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}